#!/usr/bin/env python3
"""Generate two compact indexed test images for the ST7789 firmware."""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, Sequence

WIDTH = 120
HEIGHT = 120
FRAME_SIZE = WIDTH * HEIGHT // 2
FRAME_COUNT = 2
FRAME_INTERVAL_MS = 1000

PALETTE = [
    0x0000,  # Black
    0xFFFF,  # White
    0xF800,  # Red
    0x07E0,  # Green
    0x001F,  # Blue
    0x07FF,  # Cyan
    0xF81F,  # Magenta
    0xFFE0,  # Yellow
    0x4208,  # Dark gray
    0x8410,  # Mid gray
    0xFD20,  # Orange
    0x780F,  # Purple
    0x03EF,  # Teal
    0xAFE5,  # Light green
    0xFBE0,  # Gold
    0x7BEF,  # Light blue-gray
]


def make_canvas(color: int) -> list[int]:
    """Create one row-major indexed image initialized to a palette entry."""
    return [color] * (WIDTH * HEIGHT)


def fill_rect(
    pixels: list[int], x: int, y: int, width: int, height: int, color: int
) -> None:
    """Fill a clipped rectangle in an indexed test image."""
    x0 = max(0, x)
    y0 = max(0, y)
    x1 = min(WIDTH, x + width)
    y1 = min(HEIGHT, y + height)
    for row in range(y0, y1):
        start = row * WIDTH + x0
        pixels[start : start + (x1 - x0)] = [color] * (x1 - x0)


def draw_border(pixels: list[int], color: int) -> None:
    """Draw a four-pixel border around an indexed image."""
    fill_rect(pixels, 0, 0, WIDTH, 4, color)
    fill_rect(pixels, 0, HEIGHT - 4, WIDTH, 4, color)
    fill_rect(pixels, 0, 0, 4, HEIGHT, color)
    fill_rect(pixels, WIDTH - 4, 0, 4, HEIGHT, color)


def draw_digit_one(pixels: list[int], color: int) -> None:
    """Draw a large block digit one in the center of the first image."""
    fill_rect(pixels, 55, 24, 12, 68, color)
    fill_rect(pixels, 43, 34, 12, 12, color)
    fill_rect(pixels, 42, 88, 38, 12, color)


def draw_digit_two(pixels: list[int], color: int) -> None:
    """Draw a large block digit two in the center of the second image."""
    fill_rect(pixels, 38, 24, 44, 10, color)
    fill_rect(pixels, 72, 34, 10, 26, color)
    fill_rect(pixels, 38, 55, 44, 10, color)
    fill_rect(pixels, 38, 65, 10, 25, color)
    fill_rect(pixels, 38, 88, 44, 10, color)


def build_first_image() -> list[int]:
    """Build a warm diagonal-band image with a large white digit one."""
    pixels = make_canvas(8)
    for row in range(HEIGHT):
        for column in range(WIDTH):
            band = ((column + row) // 15) % 4
            pixels[row * WIDTH + column] = (2, 10, 7, 6)[band]
    draw_border(pixels, 1)
    fill_rect(pixels, 12, 12, 24, 12, 2)
    fill_rect(pixels, 84, 96, 24, 12, 7)
    draw_digit_one(pixels, 1)
    return pixels


def build_second_image() -> list[int]:
    """Build a cool checker image with a large yellow digit two."""
    pixels = make_canvas(4)
    for row in range(HEIGHT):
        for column in range(WIDTH):
            tile = ((column // 15) + (row // 15)) & 1
            pixels[row * WIDTH + column] = 12 if tile else 4
    draw_border(pixels, 5)
    fill_rect(pixels, 12, 12, 24, 12, 5)
    fill_rect(pixels, 84, 96, 24, 12, 11)
    draw_digit_two(pixels, 7)
    return pixels


def pack_indexes(indexes: Sequence[int]) -> list[int]:
    """Pack two four-bit palette indexes into each generated byte."""
    if len(indexes) != WIDTH * HEIGHT:
        raise ValueError("invalid indexed image size")
    return [
        (indexes[offset] << 4) | indexes[offset + 1]
        for offset in range(0, len(indexes), 2)
    ]


def format_bytes(data: Iterable[int], indent: str = "        ") -> str:
    """Format byte values as compact ARMCC-compatible C initializers."""
    values = list(data)
    return ",\n".join(
        indent
        + ", ".join(f"0x{value:02X}U" for value in values[start : start + 16])
        for start in range(0, len(values), 16)
    )


def format_words(data: Iterable[int], indent: str = "    ") -> str:
    """Format RGB565 palette values as C initializers."""
    values = list(data)
    return ",\n".join(
        indent
        + ", ".join(f"0x{value:04X}U" for value in values[start : start + 8])
        for start in range(0, len(values), 8)
    )


def build_header() -> str:
    """Build declarations for the two generated indexed images."""
    return f"""#ifndef __ANIM_FRAMES_H
#define __ANIM_FRAMES_H

#include "stm32f10x.h"

#define ANIM_FRAME_WIDTH          {WIDTH}U    // Indexed source width
#define ANIM_FRAME_HEIGHT         {HEIGHT}U    // Indexed source height
#define ANIM_PIXEL_SCALE          2U      // Output scale to 240x240
#define ANIM_FRAME_SIZE           {FRAME_SIZE}U   // Packed four-bit bytes per image
#define ANIM_FRAME_COUNT          {FRAME_COUNT}U      // Number of test images
#define ANIM_FRAME_INTERVAL_MS    {FRAME_INTERVAL_MS}U   // Image hold time in ms

extern const uint16_t anim_palette[16];
extern const uint8_t anim_frames[ANIM_FRAME_COUNT][ANIM_FRAME_SIZE];

#endif
"""


def build_source(frames: Sequence[Sequence[int]]) -> str:
    """Build constant palette and packed image definitions."""
    blocks = []
    for index, frame in enumerate(frames):
        blocks.append(
            "    {\n"
            f"        /* Test image {index + 1} */\n"
            f"{format_bytes(frame)}\n"
            "    }"
        )
    return (
        '#include "anim_frames.h"\n\n'
        "const uint16_t anim_palette[16] =\n"
        "{\n"
        f"{format_words(PALETTE)}\n"
        "};\n\n"
        "const uint8_t anim_frames[ANIM_FRAME_COUNT][ANIM_FRAME_SIZE] =\n"
        "{\n"
        + ",\n".join(blocks)
        + "\n};\n"
    )


def main() -> int:
    """Generate the two firmware image files beside the current project."""
    project_root = Path(__file__).resolve().parent.parent
    output_c = project_root / "User" / "anim_frames.c"
    output_h = project_root / "User" / "anim_frames.h"
    frames = [
        pack_indexes(build_first_image()),
        pack_indexes(build_second_image()),
    ]
    output_h.write_text(build_header(), encoding="gbk", newline="\n")
    output_c.write_text(build_source(frames), encoding="gbk", newline="\n")
    print(f"generated {len(frames)} images, {FRAME_SIZE} bytes each")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
