#include "anim_frames.h"

#define FRAME_BLOCK_A \
    0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, \
    0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU

#define FRAME_BLOCK_B \
    0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, 0xFFU, \
    0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U

#define FRAME_ROW_A \
    FRAME_BLOCK_A, FRAME_BLOCK_A, FRAME_BLOCK_A, FRAME_BLOCK_A, \
    FRAME_BLOCK_A, FRAME_BLOCK_A, FRAME_BLOCK_A, FRAME_BLOCK_A

#define FRAME_ROW_B \
    FRAME_BLOCK_B, FRAME_BLOCK_B, FRAME_BLOCK_B, FRAME_BLOCK_B, \
    FRAME_BLOCK_B, FRAME_BLOCK_B, FRAME_BLOCK_B, FRAME_BLOCK_B

#define FRAME_IMAGE_A \
    FRAME_ROW_A, FRAME_ROW_A, FRAME_ROW_A, FRAME_ROW_A, \
    FRAME_ROW_A, FRAME_ROW_A, FRAME_ROW_A, FRAME_ROW_A

#define FRAME_IMAGE_B \
    FRAME_ROW_B, FRAME_ROW_B, FRAME_ROW_B, FRAME_ROW_B, \
    FRAME_ROW_B, FRAME_ROW_B, FRAME_ROW_B, FRAME_ROW_B

const uint8_t anim_frames[ANIM_FRAME_COUNT][ANIM_FRAME_SIZE] =
{
    {FRAME_IMAGE_A},
    {FRAME_IMAGE_B}
};

#undef FRAME_IMAGE_B
#undef FRAME_IMAGE_A
#undef FRAME_ROW_B
#undef FRAME_ROW_A
#undef FRAME_BLOCK_B
#undef FRAME_BLOCK_A
